/**
 * @file  main.c
 * @brief NUCLEO-F746ZG firmware — IO-Link Master + SPI Slave.
 *
 * This file contains ONLY application-level code (user code sections).
 * It is designed to be placed inside a CubeMX-generated project.
 * See nucleo/README.md for full setup instructions.
 *
 * Peripheral configuration required in CubeMX:
 *   SPI1  — Full-Duplex Slave, CPOL=0, CPHA=0, 8-bit, Hardware NSS (PA4)
 *            Pins: PA5=SCK, PA6=MISO, PA7=MOSI
 *   UART4 — Asynchronous, 38400 baud, 8N1
 *            Pins: PA0=TX, PA1=RX
 *   GPIO  — PD2 as Output (label: IOLINK_EN)
 *            PG2 as Output (label: IOLINK_WAKE)
 *   DWT   — Enable in CubeMX System Core → SYS → Timebase Source
 *
 * Logic overview:
 *   The main loop waits for the RPi5 to pull the SPI CS (NSS) line low,
 *   which triggers HAL_SPI_TransmitReceive_IT().  When the transfer
 *   completes, HAL_SPI_TxRxCpltCallback() processes the received command
 *   and updates the pre-loaded response byte for the next transaction.
 */

#include "main.h"
#include "iolink.h"
#include "stm32f7xx_hal.h"
#include <string.h>

/* --------------------------------------------------------------------------
 * HAL peripheral handles — generated by CubeMX in the same file.
 * Declare them here only if this file IS the CubeMX-generated main.c.
 * -------------------------------------------------------------------------- */
SPI_HandleTypeDef  hspi1;
UART_HandleTypeDef huart4;

/* --------------------------------------------------------------------------
 * Application state
 * -------------------------------------------------------------------------- */
static volatile uint8_t spi_rx_byte = 0x00;   /* command received from RPi5 */
static volatile uint8_t spi_tx_byte = RSP_IDLE; /* response pre-loaded for RPi5 */
static volatile uint8_t new_cmd_flag = 0;      /* set in ISR, cleared in main loop */

/* --------------------------------------------------------------------------
 * Forward declarations for CubeMX-generated init functions
 * -------------------------------------------------------------------------- */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_SPI1_Init(void);
static void MX_USART4_UART_Init(void);

/* --------------------------------------------------------------------------
 * Helpers
 * -------------------------------------------------------------------------- */
static void dwt_enable(void)
{
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL  |= DWT_CTRL_CYCCNTENA_Msk;
}

/** Arm the next non-blocking SPI slave transfer (1 byte). */
static void spi_arm_next_transfer(void)
{
    /* Cast away volatile: HAL accepts uint8_t* */
    HAL_SPI_TransmitReceive_IT(&hspi1,
                               (uint8_t *)&spi_tx_byte,
                               (uint8_t *)&spi_rx_byte,
                               1);
}

/* --------------------------------------------------------------------------
 * HAL SPI callback — called from HAL_SPI_IRQHandler in stm32f7xx_it.c
 * -------------------------------------------------------------------------- */
void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance != SPI1) return;

    /* Flag the received command for processing in the main loop */
    new_cmd_flag = 1;

    /* Re-arm immediately so the slave is always ready */
    spi_arm_next_transfer();
}

/* --------------------------------------------------------------------------
 * main
 * -------------------------------------------------------------------------- */
int main(void)
{
    /* ------------------------------------------------------------------ */
    /* HAL + clock initialisation (CubeMX-generated content goes here)    */
    /* ------------------------------------------------------------------ */
    HAL_Init();
    SystemClock_Config();
    dwt_enable();

    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_USART4_UART_Init();

    /* ------------------------------------------------------------------ */
    /* IO-Link: send wake-up pulse, wait for device startup               */
    /* ------------------------------------------------------------------ */
    iolink_init();

    /* ------------------------------------------------------------------ */
    /* Pre-load MISO with IDLE and arm the first SPI transfer             */
    /* ------------------------------------------------------------------ */
    spi_tx_byte = RSP_IDLE;
    spi_arm_next_transfer();

    /* ------------------------------------------------------------------ */
    /* Main loop                                                          */
    /* ------------------------------------------------------------------ */
    while (1)
    {
        if (!new_cmd_flag) continue;
        new_cmd_flag = 0;

        uint8_t cmd = spi_rx_byte;

        /* Ignore stale 0x00 bytes sent while RPi5 is reading status */
        if (cmd == 0x00) continue;

        uint8_t  pd_in  = 0x00;
        int      iol_rc = IOLINK_OK;

        switch (cmd)
        {
        /* ---- GRIP command ------------------------------------------- */
        case CMD_GRIP:
            iol_rc = iolink_cycle(IOLINK_PD_GRIP, &pd_in);
            if (iol_rc == IOLINK_OK) {
                /* Report GRIPPING; the RPi5 polls status next cycle */
                spi_tx_byte = RSP_GRIPPING;
            } else {
                spi_tx_byte = RSP_ERROR;
            }
            break;

        /* ---- RELEASE command ---------------------------------------- */
        case CMD_RELEASE:
            iol_rc = iolink_cycle(IOLINK_PD_RELEASE, &pd_in);
            if (iol_rc == IOLINK_OK) {
                spi_tx_byte = RSP_RELEASING;
            } else {
                spi_tx_byte = RSP_ERROR;
            }
            break;

        /* ---- STATUS request ----------------------------------------- */
        case CMD_STATUS:
            /*
             * Run a read cycle (send current PDout, read device status).
             * We re-use whatever the last pd_out was; here we send 0x00
             * (no-op / keep state) and just read back the device status.
             */
            iol_rc = iolink_cycle(IOLINK_PD_RELEASE, &pd_in);
            if (iol_rc != IOLINK_OK) {
                spi_tx_byte = RSP_ERROR;
                break;
            }
            if (pd_in & IOLINK_STATUS_GRIPPED) {
                spi_tx_byte = RSP_GRIPPING;
            } else if (pd_in & IOLINK_STATUS_OPEN) {
                spi_tx_byte = RSP_RELEASING;
            } else {
                spi_tx_byte = RSP_IDLE;
            }
            break;

        default:
            /* Unknown command — return current status unchanged */
            break;
        }
    }
}

/* --------------------------------------------------------------------------
 * CubeMX-generated peripheral init stubs
 * Replace these with the actual generated code from your CubeMX project.
 * -------------------------------------------------------------------------- */

static void SystemClock_Config(void)
{
    /*
     * CubeMX generates this function.
     * Configure PLL for 216 MHz on STM32F746ZG.
     * (Paste the generated SystemClock_Config() body here.)
     */
}

static void MX_GPIO_Init(void)
{
    /*
     * CubeMX generates this function.
     * Required pin configuration:
     *   PA0  — AF8  UART4_TX
     *   PA1  — AF8  UART4_RX
     *   PA4  — AF5  SPI1_NSS  (Hardware NSS)
     *   PA5  — AF5  SPI1_SCK
     *   PA6  — AF5  SPI1_MISO
     *   PA7  — AF5  SPI1_MOSI
     *   PD2  — GPIO Output (IOLINK_EN),   default LOW
     *   PG2  — GPIO Output (IOLINK_WAKE), default LOW
     * (Paste the generated MX_GPIO_Init() body here.)
     */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    __HAL_RCC_GPIOG_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* PD2 — IOLINK_EN (active HIGH enables the TIOL221EVM driver) */
    GPIO_InitStruct.Pin   = GPIO_PIN_2;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_2, GPIO_PIN_RESET);

    /* PG2 — IOLINK_WAKE */
    GPIO_InitStruct.Pin = GPIO_PIN_2;
    HAL_GPIO_Init(GPIOG, &GPIO_InitStruct);
    HAL_GPIO_WritePin(GPIOG, GPIO_PIN_2, GPIO_PIN_RESET);
}

static void MX_SPI1_Init(void)
{
    /*
     * CubeMX generates this function.
     * Key settings:
     *   Mode             : Slave Full-Duplex
     *   Data Size        : 8 bits
     *   CLK polarity     : Low (CPOL=0)
     *   CLK phase        : 1 Edge (CPHA=0)
     *   NSS              : Hardware Input
     *   BaudRate Prescaler: irrelevant for slave
     *   FirstBit         : MSB
     * (Paste the generated MX_SPI1_Init() body here.)
     */
    hspi1.Instance               = SPI1;
    hspi1.Init.Mode              = SPI_MODE_SLAVE;
    hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi1.Init.NSS               = SPI_NSS_HARD_INPUT;
    hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode            = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    HAL_SPI_Init(&hspi1);
}

static void MX_USART4_UART_Init(void)
{
    /*
     * CubeMX generates this function.
     * Key settings:
     *   BaudRate   : 38400  (IO-Link COM2)
     *   WordLength : 8 bits
     *   StopBits   : 1
     *   Parity     : None
     *   Mode       : TX + RX
     *   HwFlowCtl  : None
     * (Paste the generated MX_USART4_UART_Init() body here.)
     */
    huart4.Instance          = UART4;
    huart4.Init.BaudRate     = 38400;
    huart4.Init.WordLength   = UART_WORDLENGTH_8B;
    huart4.Init.StopBits     = UART_STOPBITS_1;
    huart4.Init.Parity       = UART_PARITY_NONE;
    huart4.Init.Mode         = UART_MODE_TX_RX;
    huart4.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart4.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart4);
}
